### ISSUE TITLE
Length of Means and Ranges

### ISSUE THREAD

**Issue by clazarus** [sisl/NNet#1]
Hi Kyle,

I have been running into issues with these 2 lines:

https://github.com/sisl/NNet/blob/654ca0b2393f3057c06e53a16f2aab6ccf707b48/scripts/writeNNet.py#L63-L64

I believe ranges and means should have the same length as inputSize (without the +1) or am I missing something?

Additionally, this comment:
https://github.com/sisl/NNet/blob/654ca0b2393f3057c06e53a16f2aab6ccf707b48/scripts/pb2nnet.py#L118

I believe should only refer to input and not outputs. I believe only inputs would be normalized.

Thank you!

**Comment by kjulian3** [comment]
The extra term in means/ranges is for normalizing the outputs. All of the outputs were normalized during training using the overall output mean/range value of the outputs, so the extra terms allow the network outputs to be unnormalized to approximate the original training data before normalization.

**Comment by clazarus** [comment]
I understand. Two things though,

1. How can there only be one mean and one range value for the outputs if the network can have more than one output ?

2. I understrand the purpose but I guess the behavior appears to be unexpected because if you use pb2nnet to parse a network and then load that new nnet file with this package to, for example, do a forward pass you get the error, I guess the user is expected to manually edit the nnet file to add the mean and range values, right?

Thank you.

**Comment by clazarus** [comment]
I see. I will take a look at pb2nnet. I guess I just fed it the .pb and specified the input and output ops and wasn't careful to look at means of ranges of the outputs, I only provided enough for the inputs.

Thank you very much!
