### ISSUE TITLE
Unable to read model

### ISSUE THREAD

**Issue by mswipedata** [sisl/NNet#10]
Getting the following while trying to load a model:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-46-efc0a47dcd10>", line 1, in <module>
    weights, biases = readNNet(r'C:\Users\Saikat.Sarkar\Documents\FakeImageDetection-master\FakeImageDetection-master\nnet\CNN2.nnet')
  File "<ipython-input-42-f3fc8d11dc28>", line 22, in readNNet
    line = f.readline()
  File "C:\Program Files\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3333: character maps to <undefined>

The model works well in Java

Trying to implement this project in python:
https://github.com/afsalashyana/FakeImageDetection

**Comment by kjulian3** [comment]
How were these nnet files created? The .nnet files in your project seem to be some sort of binary file written in some other nnet format. The NNet format used here describes a simple text file that specifies fully-connected ReLU networks. This format is used by networks in the Reluplex repository: https://github.com/guykatzz/ReluplexCav2017/tree/master/nnet. The scripts and functions provided in this repository were not designed to read the format used by the networks in your repository.

**Comment by kjulian3** [comment]
Looks like those files were created with Neuroph, a Java neural network framework: http://neuroph.sourceforge.net/. This .nnet format has no connection with Neuroph. It's just unfortunate that both use .nnet file extensions for network files. I'll add a comment documentation to clarify this.
