### ISSUE TITLE
Node operation type Gemm not supported

### ISSUE THREAD

**Issue by YukeWang96** [sisl/NNet#12]
Hi,

This is my Pytorch model exported to ONNX. 

```
class Net(nn.Module):
    def __init__(self):
        super(iris_net, self).__init__()
        self.fc1 = nn.Linear(4, 4, bias=True)
        self.fc2 = nn.Linear(4, 4, bias=True)
        self.fc3 = nn.Linear(4, 3, bias=True)

    def forward(self, X):
        X = F.relu(self.fc1(X))
        X = F.relu(self.fc2(X))
        X = self.fc3(X)
        return X
```

However, the converter returns me the error as 

> Node operation type Gemm not supported

Thanks a lot for your help!

**Comment by YukeWang96** [comment]
Solve it. 

just redefine the NN by using the `torch.matmul` instead of `torch.mm` for the NN operations.

Thanks

**Comment by LebronX** [comment]
> Solve it.
> 
> just redefine the NN by using the `torch.matmul` instead of `torch.mm` for the NN operations.
> 
> Thanks

Hi,

May I ask how does one redefine NN operations in pytorch?

Thanks
