### ISSUE TITLE
nnet output layer

### ISSUE THREAD

**Issue by alexopenu** [sisl/NNet#5]
It seems to me that in the evaluation methods, you do not assume that there is an output layer, consisting of ReLU neurons -- is this on purpose?

Branch "split" in my repository contains the file python/nnet_extensions.py that implements a new functionality (splitting a network into two by "cutting" it after a given layer). I added to the NNet class methods that evaluate the network with no normalization, and with a ReLU output layer, and this kind of evaluation works well with the new functionality. But if the evaluation was made on purpose with no output layer, I will have to change my implementation of the split. 

Thanks!

**Comment by kjulian3** [comment]
Yes, the NNet format assumes that hidden layers use ReLU activations and the output layer has no activation function. Benchmarks that use the NNet format comply with this assumption, so evaluating them with a final ReLU activation would give an incorrect result.

If you wanted the output layer to use a ReLU activation, you can take the outputs y from the evaluation method and pass them through max(y,0). 

NNet is a very simple format that makes assumptions like these. If you need more precise network models that differ from this format, I would suggest using Tensorflow or ONNX format. There are methods to convert NNet models to the Tensorflow or ONNX formats in the converters subfolder.

**Comment by alexopenu** [comment]
Thanks for the clarification. I like the NNet format, it is very simple,
clear,  and works well with Marabou. I'll look into ONNX, but will probably
stick with NNet. Since I am going to use the same benchmarks, and since
they comply with this format, I should anyway re-adjust my implementation.

Thanks again!

**Comment by kjulian3** [comment]
No problem!
